
app:
    path:     /
    defaults: { _controller: QlowdFtpadmBundle:Default:index }

login_route:
    path:     /login
    defaults: { _controller: QlowdFtpadmBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

qlowd_ftpadm_ftp:
    path:     /ftp
    defaults: { _controller: QlowdFtpadmBundle:Ftp:list }

qlowd_ftpadm_account:
      path:     /account
      defaults: { _controller: QlowdFtpadmBundle:Account:index }

qlowd_ftpadm_ftp_add:
    path:     /ftp/add
    defaults: { _controller: QlowdFtpadmBundle:Ftp:edit }

qlowd_ftpadm_ftp_edit:
    path:     /ftp/edit/{email}
    defaults: { _controller: QlowdFtpadmBundle:Ftp:edit, email: null }

qlowd_ftpadm_ftp_del:
    path:     /ftp/del/{email}
    defaults: { _controller: QlowdFtpadmBundle:Ftp:del, email: null }
