
app:
    path:     /
    defaults: { _controller: QlowdFtpadmBundle:Default:index }

login_route:
    path:     /login
    defaults: { _controller: QlowdFtpadmBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

qlowd_ftpadm_ftp:
    path:     /ftp
    defaults: { _controller: QlowdFtpadmBundle:Ftp:index }
