# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Qlowd\FtpadmBundle\Entity\User:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            encode_as_base64:     true
            iterations:           1024
            key_length:           40
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        db_chyro:
            entity:
              class: Qlowd\FtpadmBundle\Entity\User
              property: login
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern: ^/login$
            anonymous: ~
        security_area:
            pattern:    ^/
            http_basic: ~
            provider: db_chyro
            form_login:
                login_path: /login
                check_path: /login_check
                use_forward: false
                always_use_default_target_path: true
                default_target_path:            /
                target_path_parameter:          _target_path
                use_referer:                    false

            logout:
                path:   /logout
                target:   /
