Qlowd\FtpadmBundle\Entity\Address:
    type: entity
    table: Address
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        street:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        zipCode:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: zip_code
        city:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        country:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        phone:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        iban:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        vatNumber:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: vat_number
    manyToMany:
        customer:
            targetEntity: Customer
            cascade: {  }
            mappedBy: address
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
