Qlowd\FtpadmBundle\Entity\Ftpuser:
    type: entity
    table: FtpUser
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uid:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
        gid:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
        shell:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        access:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: none
        chroot:
            type: boolean
            nullable: false
            comment: ''
        homedirectory:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        logcount:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
        logindate:
            type: datetime
            fixed: false
            unsigned: true
            nullable: false
            comment: ''
        modifdate:
            type: datetime
            fixed: false
            unsigned: true
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
