Qlowd\FtpadmBundle\Entity\Ftpxferlog:
    type: entity
    table: FtpXferLog
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        filename:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        filesize:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
        ip:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        action:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        duration:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        logtime:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
        success:
            type: boolean
            nullable: false
            comment: ''
        syncStatus:
            type: boolean
            nullable: false
            comment: ''
            column: sync_status
    lifecycleCallbacks: {  }
