Qlowd\FtpadmBundle\Entity\User:
    type: entity
    repositoryClass: Qlowd\FtpadmBundle\Entity\UserRepository # ajouter cette ligne
    table: User
    indexes:
        customer:
            columns:
                - customer
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        fullname:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        access:
            type: boolean
            nullable: false
            comment: ''
        phone:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        isActive:
            type: boolean
            nullable: false
            comment: ''
            column: is_active
        isAdmin:
            type: boolean
            nullable: false
            comment: ''
            column: is_admin
    manyToOne:
        customer:
            targetEntity: Customer
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                customer:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
